### ISSUE TITLE
Add command to report classes without a __repr__

### ISSUE THREAD

**Issue by cleder** [cleder/crepr#51]
```
crepr report-missing <file_name> 
```

The output should be something like:
```
<filename>
line number: class name
```
It reports all classes that do not have a `__repr__`  and crepr would be able to add one.

**Comment by Sohammhatre10** [comment]
Hello @cleder 
Was trying to get this issue done but there are some issues while I try to run crepr for the `tests/run_test.py` file.
I tried modifying crepr.py and added a report-missing method to it and all the methods work really well when it comes to custom generated test file by me, but the error given below still persists only for the `run_test.py` file, any caveat on how to run tests here, is there something I'm missing?

<img width="701" alt="{D2952633-6770-4D07-9312-581D63ED749C}" src="https://github.com/user-attachments/assets/49a857c6-d9a2-4247-b382-eff0120b3318">

Here's the colab notebook for testing crepr - https://colab.research.google.com/drive/1Hi3NJjNhJ-IXCP7LB5PDXiJCAH_drBXW#scrollTo=l7XHJnueqF5F

Haven't made the changes in this notebook will add them after getting your input on the same. Thanks!:)

**Comment by Sohammhatre10** [comment]
Hello @cleder working on this issue for quite sometime, will you please assign this me.

**Comment by Sohammhatre10** [comment]
@cleder Apologies for creating these many PRs was unaware of the usage of pre-commit locally. Eventually figured it out here https://github.com/cleder/crepr/pull/63

**Comment by cleder** [comment]
Turns out with #56 this is a YAGNI and the functionality is covered
